Repository se310-t6/politicry, pull requests merged in 2022-08, with the labels that each got.

#9 docs: added README.md
  README.md
Labels: documentation

#12 feat: added boilerplate for backend pythonic code
  backend/.flake8
  backend/.gitignore
  backend/Dockerfile
  backend/dev-requirements.txt
  backend/docker-compose.yml
  backend/requirements.txt
  backend/src/main.py
  backend/tests/.gitkeep
Labels: enhancement

#11 Add contributing guidelines
  CONTRIBUTING_GUIDELINES.md
Labels: documentation

#10 Add repo templates
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/generic-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#14 Create initial backend
  .github/workflows/openapi.yml
  .gitignore
  backend/.gitignore
  backend/Dockerfile
  backend/dev-requirements.txt
  backend/openapi.oas.yml
  backend/requirements.txt
  backend/schema/down.sql
  backend/schema/up.sql
  backend/src/database.py
  backend/src/detection.py
  backend/src/main.py
  backend/src/models.py
  backend/static/assets/campfire.gif
  backend/static/notfound.html
Labels: enhancement

#23 Refactor backend to application pattern
  .flake8
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/generic-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docker.yml
  .github/workflows/openapi.yml
  .github/workflows/precommit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING_GUIDELINES.md
  README.md
  backend/.example.env
  backend/.gitignore
  backend/Dockerfile
  backend/app.py
  backend/config.py
  backend/dev-requirements.txt
  backend/docker-compose.dev.yml
  backend/docker-compose.yml
  backend/letsencrypt/.gitkeep
  backend/migrations/README
  backend/migrations/alembic.ini
  backend/migrations/env.py
  backend/migrations/script.py.mako
  backend/migrations/versions/474d2b93458f_migration.py
  backend/migrations/versions/cd94ebe9b823_migration.py
  backend/migrations/versions/eb353db7aa2b_.py
  backend/openapi.oas.yml
  backend/requirements.txt
  backend/schema/down.sql
  backend/schema/up.sql
  backend/scripts/start.sh
  backend/src/__init__.py
  backend/src/account/__init__.py
  backend/src/account/routes.py
  backend/src/database.py
  backend/src/detection.py
  backend/src/detection/__init__.py
  backend/src/detection/routes.py
  backend/src/healthcheck/__init__.py
  backend/src/healthcheck/routes.py
  backend/src/main.py
  backend/src/models.py
  backend/static/notfound.html
  backend/tests/conftest.py
  backend/tests/functional/__init__.py
  backend/tests/functional/test_detection.py
  backend/tests/pytest.ini
  backend/traefik-dynamic.dev.yml
  backend/traefik-dynamic.yml
  codecov.yml
  extension/.gitignore
  extension/package.json
  extension/public/manifest.json
  extension/src/background.ts
  extension/tsconfig.json
  extension/webpack/webpack.config.js
Labels: refactor, backend

#30 fix: fixed issues that prevented stable deployment to production
  .github/workflows/docker.yml
  backend/.example.env
  backend/docker-compose.dev.yml
  backend/docker-compose.yml
Labels: bug, backend

#35 chore: ran pre-commit hooks
  extension/public/manifest.json
  extension/public/reddit.css
Labels: refactor, frontend

#26 Reddit parsing
  extension/public/manifest.json
  extension/public/reddit.css
  extension/public/reddit.js
Labels: enhancement, frontend

#34 fix: fixed the user authorisation error, added a test to validate
  backend/Dockerfile
  backend/src/__init__.py
  backend/tests/functional/test_failed_detection.py
Labels: bug, backend

#32 feat: created a simple website as a frontend for the application, doc…
  .example.env
  .github/workflows/docker.yml
  backend/Dockerfile
  docker-compose.dev.yml
  docker-compose.yml
  letsencrypt/.gitkeep
  traefik-dynamic.dev.yml
  traefik-dynamic.yml
  website/.gitignore
  website/Dockerfile
  website/README.md
  website/assets/background.jpg
  website/assets/github.png
  website/assets/main.scss
  website/assets/panes/.gitkeep
  website/assets/profiles/angelo.jpg
  website/assets/profiles/jo.jpeg
  website/assets/profiles/lang.jpg
  website/assets/profiles/leonard.jpg
  website/assets/profiles/ryan.jpg
  website/assets/titled-logo.png
  website/components/ContentPane.vue
  website/components/NavBar.vue
  website/components/ProfileCard.vue
  website/layouts/default.vue
  website/nuxt.config.js
  website/package.json
  website/pages/index.vue
  website/static/favicon.png
  website/yarn.lock
Labels: enhancement, backend, frontend

#43 fix: fixed broken docker ci/cd
  .github/workflows/docker.yml
Labels: bug, backend

#36 Change icon
  extension/public/images/logo-128.png
  extension/public/images/logo-16.png
  extension/public/images/logo-48.png
  extension/public/manifest.json
Labels: frontend
